### ISSUE TITLE
Slack access token

### ISSUE THREAD

**Issue by nickpetrovic** [l3rt/l3rt#1]
I'm unable to post messages to slack. I created a new Slack app, gave it bot and user permissions. I've tried using both the xoxb and xoxp type tokens. I've also tied posting in public, private channels, including a direct message. 

The log is always the following:
```
04:21:55.539 [] INFO : Slack: channel=api message=some message
```

Would you be able to provide instructions on how you set up or tested the Slack target type?

**Comment by dimafeng** [comment]
@nickptrvc thank you for playing with l3rt :) 
Per your log message I can say that you're in "Log targets" mode. Please uncheck this checkbox
![screen shot 2017-10-07 at 12 37 51 am](https://user-images.githubusercontent.com/778473/31304765-cb16e16a-aaf7-11e7-99b9-e400dcea7711.png)
and try to launch the rule again. My idea was to give two modes of rule debugging - real sending of the messages or fake (with logging of the input parameters)

It seems "Log targets" is a confusing label for this checkbox. Maybe you have a better language for it?

**Comment by dimafeng** [comment]
I'm an active user of Slack, this is how it's implemented - https://github.com/l3rt/l3rt/blob/master/core/src/main/scala/lert/core/rule/target/SlackTarget.scala
Basically, it's a `POST` to `https://slack.com/api/chat.postMessage` with `token`, `channel` and `text` per https://api.slack.com/methods/chat.postMessage

**Comment by nickpetrovic** [comment]
@dimafeng thanks for responding so quickly. I think this will be an extremely useful tool, especially for those who use AWS' service of Elasticsearch. So thanks for making this project!

I completely missed that option and it does make sense when I think about what a "target" is. If I were to make a suggestion, maybe the option could be called something like "Sandbox Environment" and we could define what it means to have the sandbox option enabled? Perhaps a number of functions could fall under the sandbox option in the future. Of course, I'm stealing this idea from Jenkins pipeline as well.

![sandbox](https://user-images.githubusercontent.com/4001122/31308173-d6d70938-ab3f-11e7-81f7-bee74ab4faee.png)

**Comment by dimafeng** [comment]
@nickptrvc thank you for your feedback.
Were you able to send a message to slack? If so, I think we can close this issue.
I've created #2 to cover this misleading checkbox

**Comment by nickpetrovic** [comment]
Yep, all set!
